trigger:
  status: success
  issuers:
    # Only from PRs
    - continuous-integration/travis-ci/pr
branches:
  only:
    - /nm-/
    - t1

stack:
  imageRepo: nginx
  innerPort: 80
  outerPortRangeMin: 8000
  template:
    name: nginx-test
    target_num_containers: 1
    container_envvars:
      - key: NGINX_PORT
        value: 80
    tags:
      - mcng
      - staging
    autorestart: ALWAYS    
