trigger:
  status: success
  issuers:
    # Only from PRs
    - continuous-integration/travis-ci/pr
branches:
  only:
    - /nm-/
    - t1
    - latest

stack:
  imageRepo: dockercloud/haproxy
  innerPort: 80
  outerPortRangeMin: 8000
  template:
    name: haproxy-test
    target_num_containers: 1
    tags:
      - mcng
      - staging
    autorestart: ALWAYS    
